version: '3.8'

services:
  web:
    build: .
    command: gunicorn iranins.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:123456@db:5432/iranins
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=iranins
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

  redis:
    image: redis
    volumes:
      - redis_data:/var/lib/redis/data

  celery_worker:
    build: .
    command: celery -A iranins worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - REDIS_URL=redis://redis:6379/0

  celery_beat:
    build: .
    command: celery -A iranins beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
  redis_data: