# Generated by Django 4.2 on 2025-03-25 08:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0003_alter_insurance_insured_alter_insurance_insurer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name='amount')),
                ('start_at', models.DateField(verbose_name='start at')),
                ('end_at', models.DateField(verbose_name='end at')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='installments', to='insurance.insurance', verbose_name='installment')),
            ],
            options={
                'verbose_name': 'Installment',
                'verbose_name_plural': 'Installments',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='invoice number')),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(1, 'POS'), (2, 'Card')], verbose_name='payment type')),
                ('amount', models.PositiveBigIntegerField(verbose_name='amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('installment', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='transaction', to='transaction.installment', verbose_name='installment')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
