# Generated by Django 4.2 on 2025-03-29 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_alter_insurance_insured_alter_insurance_insurer_and_more'),
        ('transaction', '0002_alter_transaction_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='insurance.insurance', verbose_name='installment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='installment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='transaction.installment', verbose_name='installment'),
        ),
    ]
