# Generated by Django 4.2 on 2025-04-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_installment_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='is_partial',
            field=models.BooleanField(default=False, verbose_name='is partial'),
        ),
    ]
