# Generated by Django 4.2 on 2025-04-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_remove_installment_is_partial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='last_reminder_sent',
            field=models.DateField(blank=True, null=True, verbose_name='last reminder sent'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'کارتخوان'), (2, 'کارت به کارت')], default=2, verbose_name='payment type'),
        ),
    ]
