# Generated by Django 4.2 on 2025-04-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_installment_last_reminder_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'واریز'), (2, 'برداشت')], default=1, verbose_name='type'),
        ),
    ]
