# Generated by Django 4.2 on 2025-04-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_remove_transaction_payment_type_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
    ]
