# Generated by Django 4.2 on 2025-04-06 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 13, 18, 36, 649573), verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='installment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
