# Generated by Django 4.2 on 2025-04-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_alter_installment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='installment',
            name='pay_at',
            field=models.DateField(blank=True, null=True, verbose_name='pay at'),
        ),
    ]
