# Generated by Django 4.2 on 2025-04-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_rename_type_balance_balance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.PositiveBigIntegerField(verbose_name='amount'),
        ),
    ]
