# Generated by Django 4.2 on 2025-04-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_alter_balance_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='created_at',
            field=models.DateTimeField(verbose_name='created at'),
        ),
    ]
