# Generated by Django 4.2 on 2025-04-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_alter_balance_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
    ]
