services:
  db:
    image: postgres
    container_name: iranins_postgres
    environment:
      - POSTGRES_DB=iranins
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres_data:/data/postgres/open
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis
    container_name: iranins_redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped


volumes:
  postgres_data:
  redis_data:
