# Generated by Django 4.2 on 2025-03-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'مدیر'), ('support', 'پشتیبان'), ('customer', 'مدیر')], default='customer', verbose_name='role'),
        ),
    ]
