# Generated by Django 4.2 on 2025-03-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'مدیر'), (2, 'پشتیبان'), (3, 'مشتری')], default=3, verbose_name='role'),
        ),
    ]
