# Generated by Django 4.2 on 2025-04-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='on_block_list',
            field=models.BooleanField(default=False, verbose_name='on block list'),
        ),
    ]
