# Generated by Django 4.2 on 2025-03-25 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'attribute',
                'verbose_name_plural': 'attributes',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Insured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_insured', models.BooleanField(default=False, verbose_name='is insured')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='insurance.category', verbose_name='category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'insured',
                'verbose_name_plural': 'insureds',
            },
        ),
        migrations.CreateModel(
            name='InsuredAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.attribute', verbose_name='attribute')),
                ('insured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.insured', verbose_name='insured')),
            ],
            options={
                'verbose_name': 'insured attribute value',
                'verbose_name_plural': 'insured attribute values',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='start at')),
                ('end_at', models.DateTimeField(verbose_name='end at')),
                ('amount', models.PositiveBigIntegerField(verbose_name='amount')),
                ('insured', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='insurance.insured', verbose_name='insured')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='insurer')),
            ],
            options={
                'verbose_name': 'insurance',
                'verbose_name_plural': 'insurances',
            },
        ),
    ]
