# Generated by Django 4.2 on 2025-03-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='insurance_number',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='insurance number'),
        ),
    ]
