# Generated by Django 4.2 on 2025-03-25 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance', '0002_insurance_insurance_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='insured',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='insurances', to='insurance.insured', verbose_name='insured'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='insurances', to=settings.AUTH_USER_MODEL, verbose_name='insurer'),
        ),
        migrations.AlterField(
            model_name='insured',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='insureds', to='insurance.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='insured',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='insureds', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='insuredattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insureds', to='insurance.attribute', verbose_name='attribute'),
        ),
        migrations.AlterField(
            model_name='insuredattributevalue',
            name='insured',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='insurance.insured', verbose_name='insured'),
        ),
    ]
