# Generated by Django 4.2 on 2025-03-29 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance', '0003_alter_insurance_insured_alter_insurance_insurer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='insured',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='insurance.insured', verbose_name='insured'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to=settings.AUTH_USER_MODEL, verbose_name='insurer'),
        ),
        migrations.AlterField(
            model_name='insured',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insureds', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
