# Generated by Django 4.2 on 2025-03-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_alter_insurance_insured_alter_insurance_insurer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='insurance_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'شخص ثالث'), (2, 'بدنه'), (3, 'آتش سوزی'), (4, 'مسئولیت')], default=1, verbose_name='insurance type'),
        ),
    ]
