# Generated by Django 4.2 on 2025-03-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_insurance_insurance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='end_at',
            field=models.DateField(verbose_name='end at'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='start_at',
            field=models.DateField(verbose_name='start at'),
        ),
    ]
