# Generated by Django 4.2 on 2025-03-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_alter_insurance_end_at_alter_insurance_start_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insured',
            name='is_insured',
        ),
        migrations.AddField(
            model_name='insurance',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
