# Generated by Django 4.2 on 2025-04-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_remove_insured_is_insured_insurance_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='insurance number'),
        ),
    ]
